import { PLAN_LIMITS } from "@/lib/plans";
import type { DiagramCategory } from "@/lib/types";

export interface DocSection {
  id: string;
  title: string;
  paragraphs?: string[];
  steps?: string[];
  bullets?: string[];
}

export const DOC_GUIDES: { slug: string; title: string; description: string; sections: DocSection[] }[] = [
  {
    slug: "overview",
    title: "Welcome to Tingraph",
    description: "Start with an idea. Turn it into a diagram. Make the final figure your own.",
    sections: [
      { id: "what-is-tingraph", title: "A small language. A real canvas.", paragraphs: ["Tingraph turns a compact text description into an editable diagram. Write the source yourself, start from an example or ask Tingraph AI for a draft. Generate once you are ready, then move, label and style the result on the canvas.", "These docs take you from your first diagram to the details of every supported notation. Each diagram guide includes a working example, its complete syntax reference and a ready-to-copy AI tutorial prompt."] },
      { id: "the-workflow", title: "How the workflow fits together", bullets: ["Source describes what to draw. Generate parses it, calculates the layout and replaces the current drawing.", "Canvas edits finish the drawing. Moving a shape or changing a caption does not rewrite your source.", "Saving keeps both source and the final canvas, including manual edits and embedded images.", "Export creates a file for a paper, report, slide or another document."] },
      { id: "choose-a-guide", title: "Find your starting point", paragraphs: ["New here? Follow Getting started. Already drawing? Read Using the editor, Tingraph AI or Saving & exporting. Looking for a specific keyword? Open a diagram guide and jump to its syntax reference."] },
      { id: "privacy-basics", title: "Know where your work goes", paragraphs: ["The editor works on a sheet in your browser. An unsaved sheet is not a cloud backup. Saving a diagram uploads its source, canvas and embedded images to your private account.", "Asking Tingraph AI sends your request, current source, recent conversation and any attachments to the AI provider. Copying a tutorial prompt only copies text; an external assistant receives it when you choose to paste and send it there."] },
    ],
  },
  {
    slug: "getting-started",
    title: "Getting started",
    description: "Make your first editable diagram, then save or export the result.",
    sections: [
      { id: "choose-a-notation", title: "Choose the right notation", paragraphs: ["Open the diagram library and select a notation. A flowchart is a useful first choice: it has steps, decisions and arrows, without needing a large vocabulary. Every ready notation opens with a working example."], bullets: ["Process: workflows, business processes, use cases, activities and message sequences.", "Structure: reporting lines and software architecture.", "Data: entity relationships, bars, lines, shares and measured points.", "Thinking: mind maps, matrices, set overlaps and cause analysis."] },
      { id: "first-diagram", title: "Draw your first flowchart", steps: ["Open the flowchart editor using the button below.", "Open the Generate panel and select Source. Replace its text with the example below, or edit the existing example.", "Check any line-numbered error shown under the source. Correct it before generating.", "Press Generate. Tingraph arranges the elements and draws them onto the sheet.", "Select a shape on the canvas. Move it, double-click its caption to rename it, or change its ink and style.", "Save to your account or open Export to preview and download a file."] },
      { id: "source-and-canvas", title: "Before you generate again", paragraphs: ["Generate replaces the drawing from the current source. Manual canvas edits are not automatically translated back into source, so save or export a version you want to keep before generating again.", "The Source panel's Reset action also replaces source and canvas with the starter example. Its second confirmation press is deliberate."] },
      { id: "account-and-limits", title: "Create an account when you need to keep work", paragraphs: [`An account lets you save private diagrams and use account-backed generation and AI allowances. Free includes ${PLAN_LIMITS.free.diagrams} saved diagrams, ${PLAN_LIMITS.free.generations} code-to-diagram generations and ${PLAN_LIMITS.free.aiTokens.toLocaleString("en-US")} AI output tokens per 24-hour usage window.`, "You will be asked to read the policies and agree to the Terms before creating an account. Email accounts must be verified before signing in. The profile shows your plan, usage and exact reset times."] },
    ],
  },
  {
    slug: "using-the-editor",
    title: "Using the editor",
    description: "Understand source, canvas tools, direct controls and the changes that replace a sheet.",
    sections: [
      { id: "source", title: "Source is the starting point", paragraphs: ["The Generate panel has Source and Syntax guide tabs. Source contains one complete Tingraph block. The guide describes the notation currently on your sheet. A parser error identifies the line and what needs attention.", "Where a notation supports it, the direction control chooses whether the next generated drawing grows down or across. BPMN, activity and use case diagrams have their own fixed arrangements."] },
      { id: "tools", title: "Use the canvas tools", bullets: ["Pointer selects elements; Hand pans the sheet. Press 1 or V for Pointer, and 0 or H for Hand, when you are not typing.", "Hold Space to pan temporarily. Use the zoom controls or Fit to frame the drawing.", "Add shapes, text, images and freehand marks through the rail. Delete or style a selection using the offered controls.", "Choose a connector from the rail, then drag between elements. Linked connectors follow their endpoints as you move elements.", "Drag a connector's offered middle handle to adjust its route, or double-click that handle to restore the derived route.", "Keyboard shortcuts do not choose canvas tools while you are typing in a text field or source editor."] },
      { id: "graphs-and-figures", title: "Different diagrams have different controls", paragraphs: ["Graphs have independently editable elements joined by connectors: flowcharts, BPMN, org charts, use cases, activities, entity relationships and architecture diagrams.", "Figures are derived objects: charts, mind maps, matrices, Venn diagrams, fishbones and sequences. Their data and structural edits go through their direct handles or settings panel, rather than editing the shapes inside the group."], bullets: ["Select a figure or its part to reveal the controls it supports.", "Edit entity fields, architecture components or diagram boundaries with their notation-specific controls.", "Use the plus/minus controls where offered to grow or shrink the structure."] },
      { id: "style", title: "Style for the destination", paragraphs: ["The default is a formal, readable drawing. Use the Style panel to choose ink or mix a custom color, and switch between the sheet styles offered by the editor. Chart and figure settings can also control their own colors, labels and framing.", "Keep labels short, leave space for connectors and inspect the export preview at the size your document will use."] },
      { id: "keep-a-version", title: "Keep a version before replacing it", paragraphs: ["Generate, switching notation and Reset can replace the current work. Save or export a version before taking those actions. Your saved diagram includes the final canvas; a copy of source alone does not include manual finishing touches."] },
    ],
  },
  {
    slug: "tingraph-ai",
    title: "Tingraph AI & copy prompts",
    description: "Draft diagram source with the built-in assistant, or brief an assistant of your own.",
    sections: [
      { id: "built-in-ai", title: "Ask Tingraph AI", steps: ["Choose the notation first, then open Tingraph AI from the rail.", "Describe the diagram: name its elements, relationships, values or groups, and the changes you want.", "If useful, attach up to two PDF, JPEG, PNG, WebP, HEIC or HEIF files. Each file can be at most 5 MB, with a 10 MB total.", "Review the answer and its source. Returned source is checked with Tingraph's parser and layout before it is offered for generation.", "Press the reply's Generate button when you are ready. The assistant does not replace the canvas on its own."] },
      { id: "copy-a-prompt", title: "Use your own assistant", steps: ["Open the guide for the diagram you want and press Copy AI prompt.", "Paste the prompt into your chosen assistant. Replace the instruction under MY DIAGRAM with your own description.", "Ask for one complete Tingraph source block. Copy the source from the reply into the editor's Source tab.", "Check parser errors and press Generate. An external assistant can still make mistakes; the prompt is a syntax briefing, not a guarantee of correct output."] },
      { id: "write-a-good-request", title: "Make the request concrete", bullets: ["For a graph, name the elements and which elements should connect; include branch labels when relevant.", "For a chart, provide real values, units and series names. Do not ask the model to invent research data.", "For a figure, describe its hierarchy, groups, sets or message order.", "For a revision, state the one change clearly and ask to keep the other content intact."] },
      { id: "allowances", title: "Understand AI allowances", paragraphs: [`Free includes ${PLAN_LIMITS.free.aiTokens.toLocaleString("en-US")} AI output tokens per 24-hour usage window; Premium includes ${PLAN_LIMITS.premium.aiTokens.toLocaleString("en-US")}. This is a token allowance, not a fixed number of messages. The profile shows the actual reset time.`, "Requests are limited to about 3,000 input tokens, including the notation briefing and context. Long source, conversation or attachments can exceed that limit. Shorten the request and use a smaller reference if it is rejected."] },
      { id: "ai-privacy", title: "Review what you send", paragraphs: ["The built-in assistant sends your question, current source, recent conversation and attachments to Google Gemini. Tingraph does not save the chat as an account conversation history; it lives in the current browser session.", "Provider data practices depend on its API service terms. Unpaid Gemini services can use inputs and outputs for improvement and human review. A Tingraph Premium purchase does not by itself establish Google's API billing tier. Do not include secrets, sensitive personal data or material you are not entitled to share. Read the Privacy Policy before using AI."] },
    ],
  },
  {
    slug: "saving-and-exporting",
    title: "Saving & exporting",
    description: "Keep the editable sheet, or create the file your document needs.",
    sections: [
      { id: "save", title: "Save the whole diagram", steps: ["Sign in, then use Save in the editor.", "A saved diagram keeps its source, notation, direction, ink, style, final canvas and embedded image files.", "Open your saved diagrams from the library's account view or your profile. Reopen one to continue editing.", "Use the saved-diagram controls to rename or delete work you no longer need. Deletion removes the saved copy; keep your own export if you need an archive."] },
      { id: "limits", title: "Storage limits", paragraphs: [`Free can keep ${PLAN_LIMITS.free.diagrams} saved diagrams; Premium can keep ${PLAN_LIMITS.premium.diagrams}. A saved document can be at most 10 MB. Embedded images count toward that limit.`, "An unsaved browser sheet is not automatically backed up. Refreshing or leaving the editor can lose unsaved changes. If Premium expires, your account returns to Free allowances; remove unneeded diagrams if you are over the saving limit."] },
      { id: "export", title: "Preview before downloading", paragraphs: ["Open Export to inspect the output before downloading. Choose the file name, format, scale, margin and background from the controls offered in the editor."], bullets: ["PNG: lossless raster output; suitable for most documents and transparency where offered.", "JPG: smaller raster files on a white background; compression can soften fine lines.", "SVG: vector output that scales cleanly, useful for supported document and design tools.", "PDF: a single page sized to the figure, containing its rendered image.", "Scale changes raster resolution. Margin adds space around the figure. JPG and PDF use a white background."] },
      { id: "privacy", title: "Saving and downloading are different", paragraphs: ["Saving uploads the editable document to your private account. Exporting creates a file for you to download from the browser. A recipient of an exported file gets that file, not permission to your private saved diagram.", "Check for personal or confidential content before sending an export to someone else. Keep a saved diagram as well if you want to preserve the editable work."] },
    ],
  },
  {
    slug: "troubleshooting",
    title: "Troubleshooting",
    description: "Fix common source, generation, account, saving and payment issues.",
    sections: [
      { id: "syntax", title: "Source does not parse", bullets: ["Start with one complete notation block and close every brace.", "Check the reported line, then compare the keyword and arguments with that notation's syntax reference.", "Quote labels with spaces or reserved words. Keep graph IDs unique and declare an endpoint before referring to it.", "Paste only Tingraph source into the Source tab, without explanatory text or Markdown fences.", "Compare against the working example; do not reuse a keyword from a different notation."] },
      { id: "canvas", title: "The sheet looks different from the source", paragraphs: ["Manual canvas edits do not update source. This is expected: source starts the drawing, while the canvas is yours to finish. Generate again only if you want to replace the sheet with a new drawing from source.", "If you cannot see the drawing, use Fit. For charts and other figures, edit values through their handles or settings instead of changing internal shapes."] },
      { id: "usage", title: "Generation or AI is unavailable", paragraphs: ["Check that you are signed in and your email is verified. Read your plan's usage and exact reset time on the profile page. Generation and AI have separate 24-hour windows.", "If AI reports an input limit, reduce the request and references. If the service is busy or unavailable, wait and retry. Keep source you have already received; an AI failure does not require replacing the canvas."] },
      { id: "saving", title: "A diagram will not save", bullets: ["Check the saved-diagram count and your plan's limit.", "Reduce large embedded images if the document exceeds 10 MB.", "Keep the editor open and export a local copy before retrying if your connection fails.", "Sign in again if your session expired, then retry from the original editor tab."] },
      { id: "billing", title: "A payment is pending", paragraphs: ["Return to the checkout or account page to inspect the order and check its provider status. Returning from a payment page is not proof that the provider completed payment.", "Do not repeatedly pay for the same intended purchase. If an order is stuck or an accidental duplicate was paid, contact support with the account email and order ID. Do not send passwords, full card details or provider secrets."] },
      { id: "support", title: "Send a useful support request", bullets: ["Include the notation, the action you tried and the exact error message.", "Add a minimal source example with private details removed.", "For account or billing issues, include the account email and order ID where relevant.", "Report security issues privately through the Security page's contact instructions."] },
    ],
  },
];

export const DIAGRAM_DOCS: Record<DiagramCategory, { use: string; editing: string[]; tip: string }> = {
  flow: { use: "Explain a procedure, decision path or algorithm with a small set of steps and branches.", editing: ["Move boxes and rename captions directly on the canvas. Linked arrows follow their endpoints.", "Choose a flow or annotation connector from the rail. Branch captions belong on the connector."], tip: "Give decision branches explicit labels such as Yes and No. IDs identify boxes; quoted labels are what readers see." },
  bpmn: { use: "Show a business process with responsibility split across pools and lanes, plus events, tasks and gateways.", editing: ["Use the pool controls to add lanes or pools. Removing a lane also removes its contents and affected connectors.", "Use the BPMN panel for notation-specific elements; choose sequence, message or association connectors as appropriate."], tip: "Declare elements inside the lane that owns them, then write the connections. BPMN reads across its lanes rather than using the generic direction switch." },
  org: { use: "Describe reporting relationships, roles, people and advisory ties in an organization.", editing: ["Move or rename roles on the sheet and add reporting lines using the connector rail.", "Use dashed advisory ties for relationships that are not the main reporting hierarchy."], tip: "Keep the role and the person's name separate. Reporting lines use a shared rail beneath a parent so its children remain easy to read." },
  usecase: { use: "Describe what actors want to do with a system, without modeling the internal implementation.", editing: ["Move actors and use cases independently; use the boundary controls to name, add or remove a system boundary.", "Choose association, include, extend or generalization connectors from the rail."], tip: "A system boundary is an outline, not a parent that moves all its contents. Removing it leaves the use cases on the sheet." },
  activity: { use: "Model a UML activity, branching control flow or parallel work, with partitions for responsibilities.", editing: ["Rename actions and move them between partitions. Add or remove partitions with their own controls.", "Choose control-flow or object-flow connectors to match the relationship you mean."], tip: "Activity partitions are columns and the flow reads down the page. Fork/join and decision/merge nodes have different meanings; choose the right one." },
  erd: { use: "Describe a data model with entities, attributes, primary/foreign keys and cardinalities.", editing: ["Select a table to edit its fields through the panel or on-sheet row controls.", "Join relations to the specific key rows using their port dots. Edit endpoints, labels and cardinalities in the entity panel."], tip: "A relation can reference TABLE.field rather than the whole table. The ERD layout reads across so key-to-key relations meet the correct rows." },
  architecture: { use: "Map systems, services, stores and infrastructure regions, including custom component images.", editing: ["Select a component to change its type, name, image, position or size. Add and label flows through the architecture controls.", "Move and resize zones independently; they are backdrops, not containers that drag their components."], tip: "Source coordinates suggest the first layout, not a fixed pin. Generate leaves routing space and grows zones; later manual moves stay where you put them." },
  sequence: { use: "Explain interactions in time order between actors and objects, including replies and combined fragments.", editing: ["Drag lifelines across the top to reorder participants. Select a message to move it within the sequence.", "Edit the sequence through its figure controls rather than moving its internal strokes individually."], tip: "Message order is the time axis. Execution bars are derived from calls and replies; do not try to place them as separate nodes." },
  bar: { use: "Compare categorical readings, including grouped or stacked series.", editing: ["Drag a bar's end to change its reading; use the chart panel to edit categories, series and values.", "Choose orientation, grouping, labels and axes in the chart controls."], tip: "Use one reading per line for a single series. Use categories and series together when you are comparing multiple measurements." },
  line: { use: "Show a run of values over ordered categories or compare several runs on the same axis.", editing: ["Drag reading dots on the canvas or change values through the chart panel.", "Choose line shape, markers, area wash, axes and legend in the chart controls."], tip: "Keep category order meaningful. Every series must align with the categories it shares; a line is not a scatter plot of independent x/y pairs." },
  pie: { use: "Show nonnegative shares of one whole, optionally as a donut.", editing: ["Drag slice boundaries to adjust the distribution, or edit readings through the chart panel.", "Set slice labels, percentages, the donut hole and legend using the chart controls."], tip: "Use shares that genuinely belong to the same total. Use a bar chart instead when comparing values matters more than the part-to-whole relationship." },
  scatter: { use: "Plot paired measurements against two numeric axes, with optional series and a trend line.", editing: ["Drag individual points to change their coordinates; use the chart panel for exact values and named series.", "Choose axis ranges, point labels and the trend line through the chart settings."], tip: "Each point is an x/y pair. A fitted trend describes the supplied data; it does not establish causation or validate a research claim." },
  mind: { use: "Grow a hierarchy of ideas from a central concept, arranged radially, on two sides or downward.", editing: ["Select a branch to add, rename or remove content. Use the outward ring to grow a new branch.", "Drag a branch to pin its position; its subtree follows. Change branch shapes or replace a shape with an image."], tip: "Nested source blocks express parent-child structure. A branch pin affects that branch rather than rearranging all the other branches." },
  matrix: { use: "Compare rows and columns using text, numbers or qualitative marks, with optional grouped headings.", editing: ["Double-click a heading or cell to edit it. Use the plus/minus controls to add or remove whole rows and columns.", "Set grouping, heading direction, colors and table style in the matrix panel."], tip: "A matrix cell is free-form text, not necessarily a numeric reading. Keep each row aligned with the same column structure." },
  venn: { use: "Explain membership and overlap between two or three sets, with captions for the regions.", editing: ["Drag a ring to adjust overlap. Select region captions to rename them through the figure controls.", "Change set names, region text and style using the Venn panel."], tip: "Region keys identify intersections such as AB and ABC. Their captions are text; Tingraph does not infer mathematical set counts from them." },
  fishbone: { use: "Organize possible causes of an effect into categories, including nested causes.", editing: ["Select a bone to add a cause; select a cause to add a cause behind it.", "Rename captions in place and use the fishbone panel to edit categories and structure."], tip: "The title is the effect at the head. Categories organize proposed causes; the diagram itself does not prove which cause is responsible." },
};

export function docHref(slug: string): string {
  return slug === "overview" ? "/docs" : `/docs/${slug}`;
}
